name: Check binary size

on:
  pull_request:
    types: [opened, reopened, synchronize, labeled, unlabeled, ready_for_review]

jobs:
  check_size:
    runs-on: ubuntu-latest
    # Check if pull request does not have label "bloat-ok".
    if: "!contains(github.event.pull_request.labels.*.name, 'bloat-ok')"
    steps:
    - uses: actions/checkout@v3

    - name: Compare binary size for each commit
      run: |
        for commit in $(git rev-list HEAD..$GITHUB_SHA); do
          echo "Testing commit: $commit"
          git rebase --exec test/check-size.sh $commit
        done
