name: Run coverage

on: [push, pull_request]

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          # needed for codecov
          fetch-depth: 0
      - name: Install tools
        run: |
          sudo apt-get install -qqy bats iptables iproute2 jq
          # Add PPA for CRIU
          sudo add-apt-repository ppa:criu/ppa
          sudo apt-get update
          sudo apt-get install -qqy criu
      - name: Run make coverage
        run: sudo -E make coverage

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        with:
          fail_ci_if_error: true
          file: .coverage/coverage.out
          token: ${{ secrets.CODECOV_TOKEN }}
          verbose: true
